### ISSUE TITLE
Error in running lab2 practical

### ISSUE THREAD

**Issue by anikashc** [guptachetan1997/DIS-LAB#1]
How do I run the coordinator.c in Ubuntu? I tried but the output is stuck at 'Initialising the server at port 8000." Do I need to install some extra libraries?

**Comment by guptachetan1997** [comment]
This is expected. The coordinator starts and waits for some client to come online, and request a lock. So, apart from the coordinator, you need to start the clients as well.

![image](https://user-images.githubusercontent.com/17195830/132196395-29f95a69-e886-4bc2-8255-f69d5e4dfba2.png)

**Comment by anikashc** [comment]
Thanks a lot! It got resolved. Sorry for not informing before
